services:
  nyshare:
    image: ghcr.io/nikolainyegaard/nyshare:latest
    container_name: nyshare
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeme
    volumes:
      - ./data:/data
    networks:
      - proxy-fileshare
    restart: unless-stopped

networks:
  proxy-fileshare:
    external: true
